export const LOAD_USER_START = 'LOAD_USER_START';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROS = 'LOAD_USER_ERROS';

export const CREATE_USER_START='CREATE_USER_START';
export const CREATE_USER_SUCCESS='CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR='CREATE_USER_ERROR';

export const DELETE_USER_START='DELETE_USER_START';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR='DELETE_USER_ERROR';